#!/usr/bin/bash
Tmp=/tmp/$$
Tmp1=/tmp/$$_$$
Tmp2=/tmp/$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp"  >/dev/null 2>&1
rm -f "$Tmp1"  >/dev/null 2>&1
rm -f "$Tmp2"  >/dev/null 2>&1
rm -f "$Tmp3"  >/dev/null 2>&1
#================================================================
# paste -d' ' file1 file2 > output_file

source ~/bash.library



function implColomatic() {
    local tmp1="/tmp/temp_$$"
    local tmp2="/tmp/temp_$$_$$"
    local tmp3="/tmp/temp_$$_$$_$$"

    # Get the filename from the command-line argument
    filename1="$1"
    filename2="$2"

    # Check if a filenameis are provided
    if [ -z "$filename1" ]; then
      echo "Usage: <filename> <filename>"
      exit 1
    fi
    if [ -z "$filename2" ]; then
      echo "Usage: <filename> <filename>"
      exit 1
    fi

    # Check if the files exist
    if [ ! -f "$filename1" ]; then
      echo "Error: File '$filename' not found."
      exit 1
    fi
    if [ ! -f "$filename2" ]; then
      echo "Error: File '$filename' not found."
      exit 1
    fi

    sed 's/[[:space:]]*$//' "$filename1" > $tmp1
    sed 's/[[:space:]]*$//' "$filename2" > $tmp2

    # Find the longest line length
    max_len=$(wc -L "$tmp1" | awk '{print $1}')

    # Calculate the padding length
    padding_length=$((max_len + 2))

    # Iterate through each line of the file and pad it
    rm -f "$tmp3" >/dev/null 2>&1
    while IFS= read -r line; do
      printf "%-${padding_length}s\n" "$line" >> "$tmp3" # Pad to the right
    done  < "$tmp1"

    paste -d' ' "$tmp3" "$tmp2"

    rm -f "$tmp1" >/dev/null 2>&1
    rm -f "$tmp2" >/dev/null 2>&1
    rm -f "$tmp3" >/dev/null 2>&1
}

if [ $# -gt 0 ]; then  # Check if any arguments were provided
  if [ $# -eq 2 ]; then
      implColomatic "$1" "$2"
      exit 0
  fi
  if [ $# -eq 3 ]; then
      implColomatic "$1" "$2" > "$Tmp"
      implColomatic "$Tmp" "$3"
      exit 0
  fi
  if [ $# -eq 4 ]; then
      implColomatic "$1"    "$2" > "$Tmp1"
      implColomatic "$Tmp1" "$3" > "$Tmp2"
      implColomatic "$Tmp2" "$4"
      exit 0
  fi
fi
