#!/usr/bin/bash
# *********************************************************DATEOMATIC: Wed Feb 26 00:01:17 EST 2025
# *********************************************************HASHOMATIC: 77817de3816b3a115eaec6bb1cc34eea
Tmp=/tmp/$$
Tmp0=/tmp/$$_$$
Tmp1=/tmp/$$_$$_$$
Tmp2=/tmp/$$_$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp $Tmp0 $Tmp1 $Tmp2 $Tmp3"  >/dev/null 2>&1;
QUIET="NO"
while getopts "qls" arg
do
    case $arg in
        q) QUIET="YES"
           ;;
        l) echo "Tracked files with changes"
           git ls-files -m
           exit 0
           ;;
        s) echo "Staged  for commit"
           git diff --name-only --cached
           exit 0
           ;;
    esac
done
shift $(($OPTIND - 1))

if [ ! "$QUIET" == "YES" ]; then                                                                                               
    echo ""
    echo "==============================================================================================="
    echo "Lines starting with - are lines that have been removed or changed from the last commit."
    echo "Lines starting with + are lines that have been added or changed in your workspace."
    echo "Lines without a + or - are context lines that haven't changed."
    echo ""
    echo "Within each hunk, lines are prefixed with special characters to indicate their status:"
    echo "(a space): These are context lines. They are identical in both the old and new files"
    echo "By default, Git shows 3 lines of context above and below the actual changes."
    echo ""
    echo "- (minus sign): These lines are deleted from the old file or changed from the old file."
    echo "They appear in the old version but are not present (or are different) in the new version."
    echo ""
    echo "+ (plus sign): These lines are added to the new file or are the new version of a changed line."
    echo "They appear in the new version but were not present (or were different) in the old version."
    echo "==============================================================================================="
    echo ""
fi
git diff HEAD -- "$1"
