#!/usr/bin/bash
Tmp=/tmp/$$
Tmp1=/tmp/$$_$$
Tmp2=/tmp/$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp"  >/dev/null 2>&1
rm -f "$Tmp1"  >/dev/null 2>&1
rm -f "$Tmp2"  >/dev/null 2>&1
rm -f "$Tmp3"  >/dev/null 2>&1
#================================================================

source ~/bash.library

INDENT=""
DELIM=" "
BAR=""
SPACE=""
W=32

while getopts "f:o arg
do
    case $arg in
        f) 
           FILENAME="$OPTARG" 
           indent_file "$OPTARG" 
           ;;
        o) 
           cat "$FILENAME" 
           exit 0
           ;;
    esac
done
shift $(($OPTIND - 1))

