#!/usr/bin/bash
Tmp=/tmp/$$
Tmp0=/tmp/$$_$$
Tmp1=/tmp/$$_$$_$$
Tmp2=/tmp/$$_$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp $Tmp0 $Tmp1 $Tmp2 $Tmp3"  >/dev/null 2>&1;
#   >/dev/null 2>&1;

source /home/mestes/scm/basics/bash.library


UPDATE="NO"
REMOTE="YES"
while getopts "txruls" arg
do
    case $arg in
        t) UPDATE="TEST"
           ;;
        x) UPDATE="EXTRACT"
           ;;
        r) UPDATE="REMOTE"
           ;;
        u) UPDATE="REMOTE"
           ;;
        l) UPDATE="LOCAL"
           ;;
        s) UPDATE="SCAN"
           ;;
    esac
done
shift $(($OPTIND - 1))

D=`date`
core.print.critical "update $D"


if [ "$UPDATE" == "SCAN" ]; then                                                                                               
    if ! scan; then
        echo "Exiting main script."
        exit 1
    fi
    exit 1
fi

if [ "$UPDATE" == "REMOTE" ]; then                                                                                               
    if ! scan; then
        echo "Exiting main script."
        exit 1
    fi
fi
if [ "$UPDATE" == "REMOTE" ]; then                                                                                               
    core.print.info "push origin master (basics)"
    git push -u origin master

    D=`pwd`

    cd ../archernar.github.io
    cp ../basics/files/* ./files
    cp ../basics/index.html ./
    git add ./files                                   >/dev/null 2>&1;
    git add ./index.html                              >/dev/null 2>&1;
    git rm $(git ls-files --deleted ./files)          >/dev/null 2>&1;
    git commit -m "Updated ./files and index.html"    >/dev/null 2>&1;
    core.print.info "push origin master (archernar.github.io)"
    git push origin master     >/dev/null 2>&1;

    cd "$D"

    core.print.info "Remote complete"
    exit 0
fi

if [ "$UPDATE" == "EXTRACT" ]; then                                                                                               
    core.print.advice   "tagging"
    btags bash.library > tags
    core.print.info "Extract"
    rm -f modifiedfilenames  >/dev/null 2>&1;
    touch modifiedfilenames
    while IFS= read -r file_name; do
        if [[ "$file_name" == .* ]]; then
            renamecopy_dot_file "$file_name"
            file_name="$MODIFIEDFILENAME"
            git add "$MODIFIEDFILENAME"
            echo "$MODIFIEDFILENAME" >> "modifiedfilenames"
        fi

        ./codeTemplate "./$file_name" "$file_name" > "./files/$file_name.html"
        cp "./$file_name" ./files
        core.print.advice "./$file_name"
    done < "bash.tools"

    ./bashfunctionextractor
    test_file="./output"
    core.check_for_duplicates "$test_file"
    return_code=$?
    if ((return_code == 0)); then
      core.print.info "No duplicate lines found in '$test_file'."
    elif ((return_code == 1)); then
      core.print.info "Duplicate lines found in '$test_file' (see stderr for details)."
    elif ((return_code == 2)); then
      core.print.info "Error: File '$test_file' not found or not readable."
    fi


    git add ./files
    git add ./index.html
    git commit -m "Updated ./files and index.html"         >/dev/null 2>&1;
    N=`git ls-files --deleted ./files | wc -l`
    core.print.info "$N files were deleted from ./files"
    git diff --name-only ./files
    if [ "$N" -gt 0 ]; then
      core.print.info "===================================================="
      core.print.info "./files needs updating"
      git rm $(git ls-files --deleted ./files)
      core.print.info "===================================================="
    fi

    core.print.info "Extraction complete"


    D=`pwd`
    cd /tmp
    tar cvf basics.tar ~/scm/basics  >/dev/null 2>&1;
#   >/dev/null 2>&1;
    mkdir -p                     "$HOME/BACKUPS"
    mkdir -p                     "$HOME/BACKUPS_ARCHIVE"
    move_old_files "$HOME/BACKUPS"   "$HOME/BACKUPS_ARCHIVE" 60
    
    backup_file   basics.tar     ~/BACKUPS   >/dev/null 2>&1;
    cd "$D"
    core.print.advice "Backup complete"

    exit 0
fi

if [ "$UPDATE" == "TEST" ]; then                                                                                               
      ansi.clear
      core.print.echo "Test Start ==============================================="
      core.print.alltest
      core.print.echo "Test End   ==============================================="
      exit 0
fi


if [ "$UPDATE" == "YES" ]; then                                                                                               
    RETVAL="YES"                                                                                                             
else                                                                                                                         
    RETVAL="NO"                                                                                                              
fi                                                                                                                           



FILE="./.vimrc"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.alert "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "\" *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "\" *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi


FILE="./.bashrc"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi


FILE="./bashrc.shared"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi

FILE="./bash.library"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi

FILE="./gawk.library"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi

rm -f "$Tmp"  >/dev/null 2>&1;


./functionlist.bash | gawk '{sz=$0;gsub(/[(].*[)]/, "", sz);print "files/" sz ".html";}' > $Tmp1
cat modifiedfilenames >> $Tmp1
cat $Tmp1 | gawk '
BEGIN {
    BASE="https://raw.githubusercontent.com/archernar/basics/refs/heads/master/"
    BASE="https://archernar.github.io/"
}
/files./ {
    print BASE $1
}' | sort|uniq  > $Tmp

git ls-files | gawk '
BEGIN {
    BASE="https://raw.githubusercontent.com/archernar/basics/refs/heads/master/"
}
{
    print BASE $0
}' > get.raw
git add get.raw
grep bash get.raw | gawk '{print "wget " $0}' > getme
git add getme


core.print.flag
cp "$Tmp" "simple_table"
alpha_normal4 "simple_table"
create_simple_table4 "simple_table"
cat "simple_table" | sed 's/^/# /' > toc


alpha_normal4 "$Tmp"
create_markdown_table4 "$Tmp" "MAKELINKS"   >  README.md
gitadd "README.md"
core.print.info "Step 0 Complete"

cp "$Tmp" ./files/index.html
./htmlTemplate "./files/index.txt" "index.txt" > "./files/index.html"
./htmlTemplate "./files/index.txt" "index.txt" > "./index.html"
core.print.info "Step 1 Complete"



if [ "$UPDATE" == "LOCAL" ]; then                                                                                               
    git commit  -m "Update"
    git status
fi


core.print.info "Cleaning up"
rm -f zeda zedb zed zzed zerd qed qqed fed ffed xx yy xxx yyy
rm -f sfa*  >/dev/null 2>&1





# FHASH=`cat ./.vimrc | gawk  ' /HASHOMATIC/ {n=split($0,A," ");h=A[n];gsub(/ +$/, "", h);print h;}'`
