#!/usr/bin/bash
Tmp=/tmp/$$
Tmp0=/tmp/$$_$$
Tmp1=/tmp/$$_$$_$$
Tmp2=/tmp/$$_$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp $Tmp0 $Tmp1 $Tmp2 $Tmp3"  >/dev/null 2>&1;

UPDATE="NO"
while getopts "rul" arg
do
    case $arg in
        r) UPDATE="REMOTE"
           ;;
        u) UPDATE="REMOTE"
           ;;
        l) UPDATE="LOCAL"
           ;;
    esac
done
shift $(($OPTIND - 1))

if [ "$UPDATE" == "YES" ]; then                                                                                               
    RETVAL="YES"                                                                                                             
else                                                                                                                         
    RETVAL="NO"                                                                                                              
fi                                                                                                                           

D=`date`
FILE="./.vimrc"
grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
IHASH=$(md5sum "$Tmp" | awk '{print $1}')
echo "\" *********************************************************DATEOMATIC: $D"      > $Tmp1
echo "\" *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
cat $Tmp  >> $Tmp1
cat $Tmp1  > "$FILE"

FILE="./.bashrc"
grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
IHASH=$(md5sum "$Tmp" | awk '{print $1}')
echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
cat $Tmp  >> $Tmp1
cat $Tmp1  > "$FILE"

FILE="./bashrc.shared"
grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
IHASH=$(md5sum "$Tmp" | awk '{print $1}')
echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
cat $Tmp  >> $Tmp1
cat $Tmp1  > "$FILE"


rm -f zed zzed zerd qed qqed fed ffed xx yy xxx yyy moe

if [ "$UPDATE" == "LOCAL" ]; then                                                                                               
    git add .
    git commit  -m "Update"
    git status
fi
if [ "$UPDATE" == "REMOTE" ]; then                                                                                               
    git add -a;
    git commit  -m "Update"
    git push -u origin master
    git status
fi







# FHASH=`cat ./.vimrc | gawk  ' /HASHOMATIC/ {n=split($0,A," ");h=A[n];gsub(/ +$/, "", h);print h;}'`
