#!/usr/bin/bash
Tmp=/tmp/$$
Tmp0=/tmp/$$_$$
Tmp1=/tmp/$$_$$_$$
Tmp2=/tmp/$$_$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp $Tmp0 $Tmp1 $Tmp2 $Tmp3"  >/dev/null 2>&1;
#   >/dev/null 2>&1;

source /home/mestes/scm/basics/bash.library


UPDATE="NO"
REMOTE="YES"
while getopts "txruls" arg
do
    case $arg in
        t) UPDATE="TEST"
           ;;
        x) UPDATE="EXTRACT"
           ;;
        r) UPDATE="REMOTE"
           ;;
        u) UPDATE="REMOTE"
           ;;
        l) UPDATE="LOCAL"
           ;;
        s) UPDATE="SCAN"
           ;;
    esac
done
shift $(($OPTIND - 1))

D=`date`
core.print.critical "update $D"
core.print.critical "Log Level is $LOGLEVEL"


if [ "$UPDATE" == "SCAN" ]; then                                                                                               
    if ! scan; then
        echo "Exiting main script."
        exit 1
    fi
    exit 1
fi

if [ "$UPDATE" == "REMOTE" ]; then                                                                                               
    if ! scan; then
        echo "Exiting main script."
        exit 1
    fi
fi
if [ "$UPDATE" == "REMOTE" ]; then                                                                                               
    core.print.info "push origin master (basics)"
    git push -u origin master

    D=`pwd`

    cd ../archernar.github.io
    cp ../basics/files/* ./files
    cp ../basics/index.html ./
    git add ./files                                   >/dev/null 2>&1;
    git add ./index.html                              >/dev/null 2>&1;
    git rm $(git ls-files --deleted ./files)          >/dev/null 2>&1;
    git commit -m "Updated ./files and index.html"    >/dev/null 2>&1;
    core.print.info "push origin master (archernar.github.io)"
    git push origin master     >/dev/null 2>&1;

    cd "$D"

    core.print.info "Remote complete"
    exit 0
fi

if [ "$UPDATE" == "EXTRACT" ]; then                                                                                               
    core.print.info "Extract"
    rm -f modifiedfilenames  >/dev/null 2>&1;
    touch modifiedfilenames
    while IFS= read -r file_name; do
        if [[ "$file_name" == .* ]]; then
            renamecopy_dot_file "$file_name"
            file_name="$MODIFIEDFILENAME"
            git add "$MODIFIEDFILENAME"
            echo "$MODIFIEDFILENAME" >> "modifiedfilenames"
        fi

        ./codeTemplate "./$file_name" "$file_name" > "./files/$file_name.html"
        cp "./$file_name" ./files
        core.print.advice "./$file_name"
    done < "bash.tools"

    ./bashfunctionextractor
    test_file="./output"
    core.check_for_duplicates "$test_file"
    return_code=$?
    if ((return_code == 0)); then
      core.print.info "No duplicate lines found in '$test_file'."
    elif ((return_code == 1)); then
      core.print.info "Duplicate lines found in '$test_file' (see stderr for details)."
    elif ((return_code == 2)); then
      core.print.info "Error: File '$test_file' not found or not readable."
    fi


    git add ./files
    git add ./index.html
    git commit -m "Updated ./files and index.html"         >/dev/null 2>&1;
    N=`git ls-files --deleted ./files | wc -l`
    core.print.info "$N files were deleted from ./files"
    git diff --name-only ./files
    if [ "$N" -gt 0 ]; then
      core.print.info "===================================================="
      core.print.info "./files needs updating"
      git rm $(git ls-files --deleted ./files)
      core.print.info "===================================================="
    fi

    core.print.info "Extraction complete"
    exit 0
fi

if [ "$UPDATE" == "TEST" ]; then                                                                                               
      core.print.echo "===================================================="
      core.print.echo "Test"
      core.print.echo "===================================================="
      exit 0
fi


if [ "$UPDATE" == "YES" ]; then                                                                                               
    RETVAL="YES"                                                                                                             
else                                                                                                                         
    RETVAL="NO"                                                                                                              
fi                                                                                                                           



FILE="./.vimrc"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.alert "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "\" *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "\" *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi


FILE="./.bashrc"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi


FILE="./bashrc.shared"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi

FILE="./bash.library"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi

FILE="./gawk.library"
if [ $(isSameHash "$FILE") == "0" ]; then
    core.print.info "HashoMatic $FILE"
    grep -v DATEOMATIC "$FILE" | grep -v HASHOMATIC > $Tmp
    IHASH=$(md5sum "$Tmp" | awk '{print $1}')
    core.print.echo "# *********************************************************DATEOMATIC: $D"      > $Tmp1
    core.print.echo "# *********************************************************HASHOMATIC: $IHASH" >> $Tmp1
    cat $Tmp  >> $Tmp1
    cat $Tmp1  > "$FILE"
    git add "$FILE"
fi

git ls-files | gawk '
BEGIN {
    BASE="https://raw.githubusercontent.com/archernar/basics/refs/heads/master/"
}
{
    print BASE $0
}' > get.raw
git add get.raw

rm -f "$Tmp"  >/dev/null 2>&1;


grep bash get.raw | gawk '{print "wget " $0}' > getme
git add getme

#cat get.raw |sort|uniq| gawk ' {n=split($0,A,"/");print "[" A[n] "](" $0 ")"}' > $Tmp
cat get.raw | egrep -v "files[/]" |sort|uniq  > $Tmp
alpha_normal2 "$Tmp"
create_markdown_table2 "$Tmp" "MAKELINKS"   > README.md
core.print.echo ""     >> README.md
core.print.echo ""     >> README.md

ls *omatic > $Tmp
create_markdown_table4 "$Tmp"  >> README.md
core.print.echo ""     >> README.md
core.print.echo ""     >> README.md

core.print.echo "## bash.library includes"     >> README.md
core.print.echo ""     >> README.md

# grep function bash.library | grep "()" | sed 's/function //' | sed -e 's/[ ]*{$//' > $Tmp
#egrep "(function.*[(][)])|(Function-Args)" bash.library | grep "()" | sed 's/function //' | sed -e 's/[ ]*{$//' > $Tmp

./functionlist.bash > $Tmp
core.dumpfile.info "$Tmp"

cat "$Tmp" | sort | uniq > "$Tmp1"; cp "$Tmp1" "$Tmp"
N=`wc -l "$Tmp" | gawk '{print $1}'`
M=$((N % 2));
core.print.info "The function list contains $N functions"
if [ "$M" == "2" ]; then                                                                                               
    core.print.info "Adding 1 function"
    core.print.echo "zzzone()" >> "$Tmp"
fi
if [ "$M" == "1" ]; then                                                                                               
    core.print.info "Adding 1 function"
    core.print.echo "zzzone()" >> "$Tmp"
fi

cat "$Tmp" | sort | uniq > "$Tmp1"; cp "$Tmp1" "$Tmp"
N=`wc -l "$Tmp" | gawk '{print $1}'`
core.print.info "The function list contains $N functions"
N=$((N / 2));
rm -f sfa*  >/dev/null 2>&1
sed -i 's/zzz.*$/\&nbsp;/g' "$Tmp"

split -l $N "$Tmp" sf
paste -d'\n' sfaa sfab > "$Tmp"
rm -f sfa*  >/dev/null 2>&1
#create_markdown_table2 "$Tmp"  >> README.md
core.print.echo ""     >> README.md
core.print.echo ""     >> README.md

rm -f "$Tmp"  >/dev/null 2>&1;
./functionlist.bash | gawk '{sz=$0;gsub(/[(].*[)]/, "", sz);print "files/" sz ".html";}' > $Tmp1
cat modifiedfilenames >> $Tmp1

# ./functionlist.bash | gawk '{sz=$0; match(sz,/[(].*[)]/); m=substr(sz,RSTART,RLENGTH);gsub(/[(].*[)]/, "", sz); print "files/" sz ".html " sz m;}' > $Tmp1

#git ls-files | gawk '
cat $Tmp1 | gawk '
BEGIN {
    BASE="https://raw.githubusercontent.com/archernar/basics/refs/heads/master/"
    BASE="https://archernar.github.io/"
}
/files./ {
    print BASE $1
}' | sort|uniq  > $Tmp
cp $Tmp $Tmp1

cp $Tmp1 $Tmp





alpha_normal2 "$Tmp"
core.print.echo "## bash.library includes"     >> README.md
create_markdown_table2 "$Tmp" "MAKELINKS"   >> README.md

cp $Tmp1 $Tmp
alpha_normal4 "$Tmp"
create_markdown_table4 "$Tmp" "MAKELINKS"   >  README1.md






#./listing   > fed
#./listing   >> README.md
core.print.flag
core.print.info "Step 1 Complete"
pandoc --metadata title="Document" --standalone --template template.html README.md > local.html
pandoc --metadata title="Document" --standalone --template template.html README1.md > ./files/index.html
pandoc --metadata title="Document" --standalone README1.md > "$Tmp1"
cat "$Tmp1" | gawk ' /^<table>/, /^<[/]table>/ { print $0 } ' > "./files/index.txt"
cp "$Tmp" ./files/index.html
./htmlTemplate "./files/index.txt" "index.txt" > "./files/index.html"
./htmlTemplate "./files/index.txt" "index.txt" > "./index.html"

core.print.info "Step 2 Complete"
cp README1.md README.md
git add README.md

rm -f zed zzed zerd qed qqed fed ffed xx yy xxx yyy


if [ "$UPDATE" == "LOCAL" ]; then                                                                                               
    git commit  -m "Update"
    git status
fi


core.print.info "Cleaning up"
rm -f sfa*  >/dev/null 2>&1





# FHASH=`cat ./.vimrc | gawk  ' /HASHOMATIC/ {n=split($0,A," ");h=A[n];gsub(/ +$/, "", h);print h;}'`
