#!/usr/bin/bash
Tmp=/tmp/$$
Tmp0=/tmp/$$_$$
Tmp1=/tmp/$$_$$_$$
Tmp2=/tmp/$$_$$_$$_$$
Tmp3=/tmp/$$_$$_$$_$$_$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"' EXIT
rm -f "$Tmp" "$Tmp0" "$Tmp1" "$Tmp2" "$Tmp3"  >/dev/null 2>&1;
#  >/dev/null 2>&1;

STATUS="NO"
MARKDOWN="NO"
FULL="NO"
UAT="NO"
DEV="NO"
PROD="NO"
REVERSE="NO"
ROOT="NO"
JSCODE="NO"
BUILDLABEL=""
while getopts "bfsmudpirj" arg
do
    case $arg in
        b) REVERSE="YES"
           ;;
        f) FULL="YES"
           ;;
        s) STATUS="YES"
           ;;
        m) MARKDOWN="YES"
           ;;
        u) UAT="YES"
           BUILDLABEL="-UAT"
           ;;
        d) DEV="YES"
           BUILDLABEL="-DEV"
           ;;
        p) PROD="YES"
           BUILDLABEL="-PROD"
           ;;
        r) ROOT="YES"
           BUILDLABEL="-ROOT"
           ;;
        j) JSCODE="YES"
           BUILDLABEL="-JS"
           ;;
    esac
done
shift $(($OPTIND - 1))

BASHLIBHOME=..
source $BASHLIBHOME/bash.library
source $BASHLIBHOME/bash.copyandlog
source $BASHLIBHOME/bash.namevalue
source $BASHLIBHOME/bash.scanner

if [ "XSCAN" == "SCAN" ]; then                                                                                               
    rm -f scan.exceptions
    echo  "Scanning all files in $(pwd)" 
    echo  "-"
    for file in *; do
      if [[ "$file" != "bash.scanner" ]]; then
          if [[ -f "$file" ]]; then

              EXCLUDE_FILES=("xxjspdf.plugin.autotable.min.js" "jspdf.umd.min.js")
              if [[ " ${EXCLUDE_FILES[@]} " =~ " ${file} " ]]; then
                  echo "****************************************"
                  echo "Skipping: $file"
                  echo "          Found in exclusion list"
                  echo "****************************************"
                  continue
              fi

              if ! scan_for_secrets "$file"; then
                  echo -n "$(dq "$file") " >> scan.exceptions
                  echo "SECRETS EXCEPTION"
                  #echo "Exiting main script."
                  #exit 1
              fi
          fi
      fi
    done
fi


# The file where the version number is stored
VERSION_FILE="version.txt"

# Check if the version file exists. If not, create it with a default version.
if [ ! -f "$VERSION_FILE" ]; then
  echo "1.0.0" > "$VERSION_FILE"
fi

# Read the current version from the file
current_version=$(cat "$VERSION_FILE")

# Use IFS to split the version string into an array (major, minor, patch)
IFS='.' read -ra version_parts <<< "$current_version"

# Assign parts to variables
major=${version_parts[0]}
minor=${version_parts[1]}
# patch=${version_parts[2]} # Old patch number isn't needed

# Increment the minor version
new_minor=$((minor + 1))

# Reset the patch version to 0
new_patch=0

# Assemble the new version string
new_version="$major.$new_minor.$new_patch"
BUILDVERSION="$major.$new_minor.$new_patch"

# Write the new version back to the file
echo "$new_version" > "$VERSION_FILE"

# Print the new version to the console
echo "Version updated to $new_version"
info "Start..."
mkdir -p ./tmp      >/dev/null 2>&1;
rm ./tmp/*          >/dev/null 2>&1;
rm -f ./text.txt

if [ "NO" == "YES" ]; then
EXCLUDE_FILES=("jspdf.plugin.autotable.min.js" "jspdf.umd.min.js")

for JS in *.min.js; do
    if [[ " ${EXCLUDE_FILES[@]} " =~ " ${JS} " ]]; then
        echo "Skipping: $JS (Found in exclusion list)."
        continue
    fi
    if [ -f "$JS" ]; then
        NOTHING=0
        # rm "$JS"
    fi
done

for JS in *.js; do
    # Check if the file actually exists (prevents running on literal "*.js" if no files are present)
    if [[ " ${EXCLUDE_FILES[@]} " =~ " ${JS} " ]]; then
        echo "Skipping: $JS (Found in exclusion list)."
        continue
    fi
    if [ -f "$JS" ]; then
        filename="${JS##*/}"
        basename="${filename%.*}"
        echo "$basename"
        #terser $basename.js -o $basename.min.js -c -m --source-map "url=$basename.min.js.map"
    fi
done

fi



./questions > questions.html

cp questions.html  text.html

THISBUILDFOLDER=./BUILDS/$BUILDVERSION$BUILDLABEL
info "$BUILDVERSION"
info "$THISBUILDFOLDER"

mkdir -p ./BUILDS
mkdir -p $THISBUILDFOLDER
# gawk '{printf "%s", $0}' questions.html > $Tmp
cp questions.html  $Tmp
N=$(grep topic-card $Tmp | wc -l)
echo "s/EXTRAEXTRA/: $N Questions/" > $Tmp1
sed -i -f $Tmp1 $Tmp

cat $Tmp           > questions.html
cat questions.html > javaexercises.html
cat questions.html > index.html
cat questions.html > error.html
if [ "$MARKDOWN" == "YES" ]; then
    #find ./markdown  -maxdepth 1 -type f -not -name "a*" -delete

    rm -f "./markdown/azed.md"
    rm -f "$Tmp2"   >/dev/null 2>&1;
    for file in ./tmp/*.md; do
         infoc "processing $file"
#        ../justomatic -n 80 -f "$file"

         while IFS= read -r line; do
           justify_line "$line" "80" >> $Tmp2
         done < "$file"
         cp "$Tmp2" "$file"

         filename="${file##*/}"
         basename="${filename%.*}"
         first_char=${basename:0:1}
         lower_first_char=${first_char,}
         mkdir -p "./markdown/$lower_first_char"
         sed -i '4,$s/^/    /g' "$file"

         #cat "$file" >> "./markdown/azed.md"
         mv "$file" "./markdown/$lower_first_char"
         #git rm "./markdown/$basename.md"
         #pandoc "$file" -o "./markdown/$basename.html"
         rm -f "$Tmp2"
    done
fi

#gawk '{printf "%s", $0}' questions.html > javaexercises.html
#gawk '{printf "%s", $0}' questions.html > index.html
#gawk '{printf "%s", $0}' questions.html > error.html
#THEFILES
FILES=( \
"myPDF.js" "bashref.html" "Java.html" "version.txt" "domathon.html" "ScannerClass.pdf" "icon.png" "index.html" "error.html" "questions.html" \
"cssref.html" "myModule.js" "logger.js" "vimref.html" "vimrefadv.html" "vimrefsim.html"\
"javaexercises.html" "banner4.png" "myQuery.js" "countdown.js" "questions.js" "editor.js" "questions.css"  \
"jspdf.plugin.autotable.min.js" "jspdf.umd.min.js" "jsdomref.html" "domref.html" "tog.css"  "JavaReference.html" "Java.html" \
)

JAVAFILES=(`ls *.java | commatize`)

PDFS=("../PDF/RangerHandbook.pdf" "../PDF/RangerHandbookNewer.pdf" "../PDF/VimFlashCards.pdf")

XHTMLFILES=("ScannerClass.pdf" "index.html" "error.html" "questions.html" "javaexercises.html")
HTMLFILES=("pages" "icon.png" "ScannerClass.pdf" "index.html" "questions.css")

if [ "COPY" == "NO" ]; then
        #for file in "${PDFS[@]}"; do
        # #################################################################################
        rm -f "$Tmp2"   >/dev/null 2>&1;
        for file in ../PDF/*.pdf; do
            if [ -f "$file" ]; then
                echo "$file"   >> "$Tmp2"
            fi
        done
        cat "$Tmp2" | sort | uniq > "$Tmp3"
        while IFS= read -r file; do
            if [ -f "$file" ]; then
                copy_and_log_noclobber "$file"           "/var/www/html"
            fi
        done < "$Tmp3"
        rm -f "$Tmp2"   >/dev/null 2>&1;
        rm -f "$Tmp3"   >/dev/null 2>&1;
        # #################################################################################
        for file in ../ALLFILES/*.pdf; do
            if [ -f "$file" ]; then
                echo "$file"   >> "$Tmp2"
            fi
        done
        cat "$Tmp2" | sort | uniq > "$Tmp3"
        while IFS= read -r file; do
            if [ -f "$file" ]; then
                copy_and_log_noclobber "$file"           "/var/www/html"
            fi
        done < "$Tmp3"
        rm -f "$Tmp2"   >/dev/null 2>&1;
        rm -f "$Tmp3"   >/dev/null 2>&1;
        # #################################################################################
fi

        for file in "${JAVAFILES[@]}"; do
            if [ -f "$file" ]; then
                copy_and_log "$file"           "$THISBUILDFOLDER"
                copy_and_log "$file"           "/var/www/html"
            fi
        done
        for file in "${FILES[@]}"; do
            if [ -f "$file" ]; then
                copy_and_log "$file"           "$THISBUILDFOLDER"
                copy_and_log "$file"           "/var/www/html"
            fi
        done
        copy_and_log "pages"           "/var/www/html"


B=happyahab
B=javaexercises.itlearningresources.com
#http://javaexercises.itlearningresources.com.s3-website.us-east-2.amazonaws.com
EP=http://$B.s3-website.us-east-2.amazonaws.com







if command -v "aws" &> /dev/null
then
    # If the exit code is 0, the command exists.
    if [ "$ROOT" == "YES" ]; then
        aws --profile default s3 rm --recursive         s3://$B/UAT
        for file in "${FILES[@]}"; do
            if [ -f "$file" ]; then
                aws --profile default s3 cp $file   s3://$B/$file  --acl public-read
            fi
        done
        echo "    $EP/javaexercises.html"
    fi
    if [ "$UAT" == "YES" ]; then
        aws --profile default s3 rm --recursive         s3://$B/UAT
        for file in "${FILES[@]}"; do
            if [ -f "$file" ]; then
                aws_copy_and_log "$file"  "s3://$B/$file"
                # aws --profile default s3 cp $file   s3://$B/UAT/$file  --acl public-read
            fi
        done
        echo "    $EP/UAT/javaexercises.html"
    fi
    if [ "$DEV" == "YES" ]; then
        aws --profile default s3 rm --recursive         s3://$B/DEV
        for file in "${FILES[@]}"; do
            if [ -f "$file" ]; then
                aws --profile default s3 cp $file   s3://$B/DEV/$file  --acl public-read
            fi
        done
        echo "    $EP/DEV/javaexercises.html"
    fi
    if [ "$PROD" == "YES" ]; then
        aws --profile default s3 rm --recursive         s3://$B/$PROD/
        rm -f changes
        for file in "${FILES[@]}"; do
            if [ -e "$file" ]; then
                ./hashme status "$file" >>  changes
            fi
        done
        CHANGES=(`cat changes`)
        echo "$CHANGES"

        for file in "${CHANGES[@]}"; do
            echo "AWS COPY:  $file"
            if [ -e "$file" ]; then
                aws_copy_and_log "$file"   "s3://$B/PROD/$file"
                aws_copy_and_log "$file"   "s3://$B/$file"
            else
            echo "AWS COPY FILE NOT EXIST:  $file"
            fi
        done
        echo "    $EP/PROD/javaexercises.html"
        echo "    $EP/javaexercises.html"
    fi

    if [ "$REVERSE" == "YES" ]; then
        for file in "${FILES[@]}"; do
            echo "AWS REVERSE COPY:  s3://$B/PROD/$file"
            aws_reverse_copy_and_log "s3://$B/PROD/$file" "$file"
        done
    fi

    if [ "$FULL" == "YES" ]; then
        aws --profile default s3 rm --recursive         s3://$B/$PROD/
        for file in "${FILES[@]}"; do
            if [ -e "$file" ]; then
                #aws_copy_and_log "$file"   "s3://$B/PROD/$file"
                aws_copy_and_log "$file"   "s3://$B/$file"
                #aws_sync_and_log "s3://$B/PROD/$file"  "s3://$B/$file"
            fi
        done
        echo "    $EP/PROD/javaexercises.html"
        echo "    $EP/javaexercises.html"
        ./hashme init .
    fi
    if [ "$STATUS" == "YES" ]; then
        rm -f changes
        for file in "${FILES[@]}"; do
            if [ -e "$file" ]; then
                ./hashme status "$file" >>  changes
                ./hashme status "$file" 
            fi
        done
        echo "    $EP/PROD/javaexercises.html"
        echo "    $EP/javaexercises.html"
    fi

    if [ "$JSCODE" == "YES" ]; then
        aws --profile default s3 rm s3://$B/$PROD/questions.js
        aws --profile default s3 rm s3://$B/questions.js
        if [ -e "questions.js" ]; then
            aws_copy_and_log "questions.js" "s3://$B/PROD/questions.js"
            aws_copy_and_log "questions.js" "s3://$B/questions.js"
        fi

        echo "    $EP/PROD/javaexercises.html"
        echo "    $EP/javaexercises.html"
    fi

else
    # If the exit code is non-zero, the command does not exist.
    echo ""
    echo "Error: Command 'aws' not found. Skipping AWS deploy."
fi
rm -f questions.count
rm -f questions.lst
# rm -f questions.topics
rm -f questions.sorted
rm -f fed zed fedd zedd qed qedd
# ls -l /var/www/html


info "Done..."
