"Which of the following is NOT a primitive data type in Java?","int","String","boolean","char","B"
"What is the output of the following code snippet? `System.out.println(10 / 3);`","3.33","3.0","3","Compilation Error","C"
"Which keyword is used to prevent a method from being overridden in a subclass?","static","final","abstract","private","B"
"What is the process of defining more than one method in a class with the same name but with different parameter lists called?","Method Overriding","Method Overloading","Inheritance","Polymorphism","B"
"Which of these keywords is used to manually throw an exception in Java?","try","catch","throw","throws","C"
"What is the default value of a boolean variable in Java?","true","false","0","null","B"
"Which collection class in Java is synchronized and thread-safe?","ArrayList","LinkedList","Vector","HashMap","C"
"How do you correctly declare a constant in Java that is accessible to all instances of a class?","`final int MY_CONST = 10;`","`static int MY_CONST = 10;`","`public static final int MY_CONST = 10;`","`const int MY_CONST = 10;`","C"
"What does the `super` keyword refer to in Java?","The current instance of the class.","The superclass of the current object.","A static context.","The child class of the current object.","B"
"Which access modifier provides the most restrictive access level?","public","protected","default","private","D"
"What is the main purpose of the `finally` block in a try-catch-finally statement?","To execute code regardless of whether an exception is thrown or not.","To catch exceptions that were not caught by the catch block.","To re-throw an exception.","To execute code only when an exception occurs.","A"
"Which of the following creates an immutable string in Java?","`String s = ""hello"";`","`StringBuilder s = new StringBuilder(""hello"");`","`StringBuffer s = new StringBuffer(""hello"");`","`char[] s = {'h','e','l','l','o'};`","A"
"In Java, what is an interface?","A class that can be instantiated.","A blueprint of a class that has static methods and final fields.","A collection of abstract methods.","A class that can only be extended once.","C"
"What is the output of `""hello"".substring(1, 3)`?","hel","ell","el","he","C"
"Which loop is guaranteed to execute at least once?","for loop","while loop","do-while loop","enhanced for loop","C"
"Which of the following is the correct syntax to declare a two-dimensional array in Java?","`int[][] arr;`","`int arr[][];`","`int[] arr[];`","All of the above","D"
"What is the purpose of the `transient` keyword in Java?","To mark a field to be serialized.","To mark a field to not be serialized.","To mark a method as thread-safe.","To mark a class as final.","B"
"Which of these is NOT a feature of Java?","Object-Oriented","Platform Independent","Pointers","Multithreaded","C"
"What does the `hashCode()` method of the `Object` class return?","A memory address of the object.","An integer representation of the object's memory address.","A unique ID for the object.","A random number.","B"
"Which statement is true about an abstract class?","It cannot have a constructor.","It can be instantiated.","It can have both abstract and non-abstract methods.","It must have all abstract methods.","C"
"What is the result of `5 | 3` (bitwise OR)?","2","5","7","8","C"
"Which of these is a checked exception?","`ArithmeticException`","`NullPointerException`","`IOException`","`ArrayIndexOutOfBoundsException`","C"
"What is the primary interface for the Java Collections Framework?","`List`","`Set`","`Map`","`Collection`","D"
"How can you make a copy of an ArrayList `list1` into `list2`?","`ArrayList<E> list2 = new ArrayList<>(list1);`","`ArrayList<E> list2 = list1;`","`ArrayList<E> list2 = list1.clone();`","`ArrayList<E> list2 = (ArrayList<E>) list1.copy();`","A"
"What is autoboxing in Java?","The automatic conversion of a primitive data type into its corresponding wrapper class object.","The automatic conversion of a wrapper class object into its corresponding primitive data type.","The process of boxing a value in a try-catch block.","The process of creating a new object from a class.","A"
"Which method must be implemented by a class that implements the `Runnable` interface?","`start()`","`run()`","`execute()`","`init()`","B"
"What is the correct way to make a String uppercase in Java?","`str.toUpper();`","`str.toUpperCase();`","`str.upper();`","`String.toUpperCase(str);`","B"
"In Java, what is the `this` keyword used for?","To refer to the current instance of the class.","To call a method of the superclass.","To create a new instance of a class.","To refer to a static method of the class.","A"
"Which collection provides an ordered collection (sequence) and may contain duplicates?","`Set`","`List`","`Map`","`Queue`","B"
"What is the use of the `instanceof` operator?","To check if an object is an instance of a specific class or an interface.","To create an instance of a class.","To compare two object instances.","To access a static member of a class.","A"
"Which class is the immediate superclass of all classes in Java?","`Main`","`System`","`Object`","`Class`","C"
"What is the output of the following? `String s1 = ""Java""; String s2 = new String(""Java""; System.out.println(s1 == s2);`","true","false","Compilation Error","Runtime Error","B"
"What is the purpose of a constructor?","To destroy an object.","To initialize the state of an object.","To create a static reference.","To be called before an object is created.","B"
"Which of these keywords cannot be used for a class declaration?","`public`","`abstract`","`final`","`private`","D"
"Which method is used to get the length of an array in Java?","`length()`","`size()`","`length`","`getSize()`","C"
"What is polymorphism?","The ability of an object to take on many forms.","The process of hiding implementation details.","The process of acquiring properties from another class.","The process of creating multiple methods with the same name.","A"
"Which of these is NOT a valid Java identifier?","`_myVariable`","`$myVariable`","`myVariable1`","`1myVariable`","D"
"What is the `classpath` in Java?","A path to the Java source files.","A path to where the JVM should look for user-defined classes and packages.","A path to the Java installation directory.","A path to the compiled .class files.","B"
"Which of the following is true about `StringBuilder` and `StringBuffer`?","`StringBuilder` is synchronized, `StringBuffer` is not.","`StringBuffer` is synchronized, `StringBuilder` is not.","Both are synchronized.","Both are not synchronized.","B"
"What is an enum in Java?","A special data type that enables for a variable to be a set of predefined constants.","An annotation used for documentation.","A type of loop.","A primitive data type.","A"
"Which statement best describes garbage collection in Java?","The programmer must manually manage memory.","The JVM automatically reclaims memory of objects that are no longer reachable.","It is the process of collecting unused .class files.","It is a way to handle exceptions.","B"
"Which access modifier allows access to members within the same package and subclasses?","`public`","`private`","`protected`","`default`","C"
"What is method overriding?","Defining a method in a subclass with the same name and parameters as a method in its superclass.","Defining multiple methods in the same class with the same name but different parameters.","Defining a method that cannot be inherited.","Defining a method that is shared among all instances of a class.","A"
"Which of the following creates a `Set` that maintains the insertion order of elements?","`HashSet`","`TreeSet`","`LinkedHashSet`","`SortedSet`","C"
"What will happen when you try to compile and run the following code? `public class Test { public static void main(String[] args) { byte b = 128; System.out.println(b); } }`","It prints 128.","It prints -128.","Compilation Error.","Runtime Error.","C"
"What is the `volatile` keyword used for?","To indicate that a variable's value will be modified by different threads.","To prevent a variable from being serialized.","To make a variable constant.","To declare a variable that is shared by all instances of a class.","A"
"Which of these classes can be used to read input from the console?","`File`","`Reader`","`Scanner`","`SystemReader`","C"
"What is the difference between `==` and `.equals()` for `String` objects?","There is no difference.","`==` compares object references, while `.equals()` compares the string values.","`.equals()` compares object references, while `==` compares the string values.","`==` is used for primitives, `.equals()` is used for objects.","B"
"What is a marker interface?","An interface with no methods or fields.","An interface that marks a class for serialization.","An interface that can only be implemented by one class.","An interface with a single abstract method.","A"
"Which of the following is an example of a Functional Interface?","`Serializable`","`Runnable`","`Cloneable`","`List`","B"
"What is the output? `System.out.println(""Result: "" + 2 + 3);`","Result: 5","Result: 23","Compilation Error","Result: 2 3","B"
"What does the `static` keyword mean when applied to a method?","The method can only be called from static contexts.","The method belongs to the class, not a specific instance.","The method cannot be overridden.","The method is thread-safe.","B"
"Which statement is used to stop a loop and continue with the next statement after the loop?","`return`","`continue`","`break`","`exit`","C"
"In an inheritance hierarchy, a subclass is also known as a...","Superclass","Derived class","Parent class","Base class","B"
"What is encapsulation?","The ability of an object to take on many forms.","The process of wrapping data and methods into a single unit.","The process of acquiring properties from another class.","The process of hiding the implementation details.","B"
"Which data structure is implemented by the `HashMap` class?","Tree","Stack","Queue","Hash table","D"
"What is the return type of the `main` method?","`int`","`void`","`String`","`boolean`","B"
"Which of the following is true about a `final` class?","It can be subclassed.","It cannot be subclassed.","It can only have final methods.","It must have a private constructor.","B"
"What is the `super()` call used for in a constructor?","To call the constructor of the superclass.","To call a method of the superclass.","To refer to the current object's superclass.","To create an instance of the superclass.","A"
"What is the default layout manager for a `JFrame`?","`FlowLayout`","`GridLayout`","`BorderLayout`","`BoxLayout`","C"
"Which operator is used for ternary conditional logic?","`?:`","`&&`","`||`","`??`","A"
"Which method of the `Object` class is used to get a string representation of an object?","`getString()`","`toString()`","`valueOf()`","`getName()`","B"
"What is the purpose of the `package` statement in Java?","To group related classes and interfaces.","To import classes from another package.","To define the entry point of the application.","To set the version of the Java compiler.","A"
"Which of the following collections stores elements in a sorted order?","`ArrayList`","`HashSet`","`TreeSet`","`LinkedList`","C"
"What is a 'checked' exception?","An exception that is checked at runtime.","An exception that must be declared in a `throws` clause or caught in a `try-catch` block.","An exception that inherits from `RuntimeException`.","An exception that cannot be caught.","B"
"What does the `finally` block do in a `try-catch` statement?","It is executed only if an exception occurs.","It is executed only if no exception occurs.","It is always executed, regardless of whether an exception occurs.","It is used to re-throw an exception.","C"
"Which of these is the correct way to start a thread in Java?","`thread.run();`","`thread.start();`","`thread.init();`","`thread.execute();`","B"
"What is the concept of 'write once, run anywhere'?","Code written on one platform can be compiled to run on any other platform.","Code compiled into Java bytecode can run on any platform with a JVM.","Java code can be written in any text editor.","Java applications can be deployed on any web server.","B"
"Which of these interfaces is NOT part of the Java Collections Framework?","`Iterable`","`Serializable`","`Comparator`","`Map`","B"
"What is the difference between `throw` and `throws`?","`throw` is used to declare an exception, `throws` is used to trigger one.","`throw` is used to trigger an exception, `throws` is used to declare that a method may throw an exception.","Both are used to trigger an exception.","Both are used to declare an exception.","B"
"Which `Map` implementation guarantees that the order of elements will be the same as the insertion order?","`HashMap`","`TreeMap`","`Hashtable`","`LinkedHashMap`","D"
"What is a lambda expression in Java 8?","A way to create anonymous classes.","An anonymous function that can be treated as a first-class citizen.","A new type of loop.","A way to handle exceptions.","B"
"Which of these is a correct declaration of a method that does not return any value?","`int myMethod() {}`","`void myMethod() {}`","`myMethod() {}`","`return myMethod() {}`","B"
"What is the purpose of the `break` statement in a `switch` block?","To terminate the `switch` statement and transfer control to the statement following the `switch`.","To skip the current case and move to the next.","To indicate the default case.","To return a value from the `switch` block.","A"
"Which data type would you use to store a single character?","`string`","`char`","`character`","`int`","B"
"What is abstraction?","The process of hiding implementation details and showing only functionality to the user.","The process of acquiring properties from another class.","The ability of an object to take on many forms.","The process of wrapping data and methods into a single unit.","A"
"Which of the following is true about interfaces in Java?","An interface can be instantiated.","An interface can contain implemented methods (with default keyword).","An interface can have a constructor.","A class can implement only one interface.","B"
"What is the result of `10 % 3`?","1","3","0","3.33","A"
"Which of these methods is used to compare two strings for equality, ignoring case differences?","`equals()`","`equalsIgnoreCase()`","`compareTo()`","`compareToIgnoreCase()`","B"
"What is the 'diamond problem' in the context of multiple inheritance?","A problem with memory allocation.","An ambiguity that can arise when a class inherits from two classes that have a common superclass.","A performance issue with inheritance.","A security vulnerability in Java.","B"
"Which design pattern provides a way to create objects without specifying the exact class of object that will be created?","Singleton","Factory","Observer","Builder","B"
"What is the purpose of the `assert` keyword?","To declare a variable.","To define a condition that must be true at a certain point in the code.","To create an instance of a class.","To handle an exception.","B"
"Which stream in Java is used for reading character data?","`InputStream`","`OutputStream`","`Reader`","`Writer`","C"
"What is the `synchronized` keyword used for?","To control access to shared resources by multiple threads.","To serialize an object.","To declare a constant.","To make a method final.","A"
"What is the difference between an `ArrayList` and a `LinkedList`?","`ArrayList` is better for random access, `LinkedList` is better for insertions and deletions.","`LinkedList` is better for random access, `ArrayList` is better for insertions and deletions.","`ArrayList` is synchronized, `LinkedList` is not.","`LinkedList` can contain duplicate elements, `ArrayList` cannot.","A"
"What is the purpose of the `default` keyword in an interface?","To specify the default value of a variable.","To provide a default implementation for a method.","To define the default constructor.","To mark the default package.","B"
"Which of these is not a loop construct in Java?","`for`","`while`","`repeat...until`","`do...while`","C"
"What does `System.gc()` do?","It forces the garbage collector to run immediately.","It requests that the JVM run the garbage collector.","It frees all memory used by the program.","It crashes the program.","B"
"What is a 'deep copy' of an object?","A copy where the fields of the new object refer to the same objects as the original.","A copy where a new object is created, and the fields of the original object are recursively copied.","A copy of the object's reference.","A copy that is performed by the `clone()` method.","B"
"Which of the following is a primitive type?","`String`","`Double`","`Integer`","`long`","D"
"What is the role of the `ClassLoader` in Java?","To load source code files.","To compile Java code into bytecode.","To load class files into the JVM at runtime.","To link the bytecode with native code.","C"
"Which of these statements is false?","A class can implement multiple interfaces.","A class can extend multiple classes.","An interface can extend multiple interfaces.","An abstract class can have non-abstract methods.","B"
"What is the output of `Math.round(2.6)`?","2","2.0","3","3.0","C"
"Which class is used for high-precision arithmetic?","`Math`","`BigDecimal`","`Double`","`Float`","B"
"What is the `Stream` API in Java 8 used for?","Processing sequences of elements in a functional style.","Reading and writing data to files.","Managing network connections.","Creating graphical user interfaces.","A"
"What is the `Optional` class used for in Java 8?","To represent a value that may or may not be present.","To make a method's return type optional.","To provide an alternative to `try-catch` blocks.","To create optional parameters for methods.","A"
"Which of these is a correct way to create a `HashMap`?","`HashMap<String, Integer> map = new HashMap<>();`","`HashMap map = new HashMap<String, Integer>();`","`Map<String, Integer> map = new HashMap();`","All of the above are correct.","D"
"What is a 'varargs' in Java?","A variable that can hold multiple types of data.","A method parameter that can accept a variable number of arguments.","A type of generic class.","A constant variable.","B"
"Which of these is the root of the Java exception hierarchy?","`Exception`","`Error`","`RuntimeException`","`Throwable`","D"
"What is the purpose of the `transient` keyword?","To indicate that a field should not be serialized.","To indicate that a field is thread-safe.","To make a field volatile.","To mark a field as temporary.","A"
"In Java, are objects passed by reference or by value?","By reference.","By value.","It depends on the object type.","Primitives are by value, objects are by reference.","B"
"What does the `finalize()` method do?","It is called just before an object is garbage collected.","It finalizes the state of an object.","It is a synonym for the `finally` block.","It must be called to destroy an object.","A"
"Which of the following is NOT a component of a Java `for` loop?","Initialization","Termination","Increment/Decrement","Condition","D"
"What is the difference between `i++` and `++i`?","`i++` increments then returns, `++i` returns then increments.","`i++` returns then increments, `++i` increments then returns.","There is no difference.","`++i` is more efficient.","B"
"Which of the following can a `switch` statement not evaluate?","`byte`","`int`","`String`","`double`","D"
"What is a 'javadoc'?","A tool for generating API documentation from source code comments.","The Java compiler.","The Java runtime environment.","A Java debugger.","A"
"Which of these classes is immutable?","`StringBuilder`","`Date`","`String`","`ArrayList`","C"
"What is the purpose of the `serialVersionUID`?","To provide a unique ID for a class during serialization.","To specify the version of the Java compiler.","To set the version number of a software application.","To identify a serialized object.","A"
"Which method is called when an object is created?","`init()`","The constructor","`create()`","`main()`","B"
"What is the `JIT` compiler?","Just-In-Time compiler, which compiles bytecode into native machine code at runtime.","Java Interface Tool, for creating user interfaces.","Java Invocation Target, for remote method calls.","Java Incremental Tester, for unit testing.","A"
"Which keyword is used to refer to the immediate parent class object?","`this`","`self`","`parent`","`super`","D"
"What is the result of `"" + 1 + 2 + ""3""`?","""33""","""123""","""6""","Compilation Error","B"
"Which of the following is true about a static method?","It can access instance variables directly.","It can be called without creating an instance of the class.","It can be overridden by a subclass.","`this` keyword can be used inside it.","B"
"What is an 'anonymous inner class'?","A class without a name, declared and instantiated at the same time.","A class that cannot be instantiated.","A class defined inside another class.","A private class.","A"
"Which of the following must be the first statement in a constructor?","A call to `super()` or `this()`.","Variable initialization.","A call to a method.","Any valid Java statement.","A"
"What is the purpose of the `continue` statement?","To exit a loop.","To skip the current iteration of a loop and move to the next.","To continue to the next case in a switch statement.","To pause the execution of a program.","B"
"Which of these must be handled or declared to be thrown?","`Error`","`RuntimeException`","`Checked Exception`","All of the above","C"
"What is the file extension for a compiled Java class file?","`.java`","`.class`","`.exe`","`.jar`","B"
"Which keyword is used to declare a variable that holds a value that cannot be changed?","`static`","`final`","`const`","`let`","B"
"What is the entry point for any Java application?","`run()`","`start()`","`main()`","`execute()`","C"
"Which symbol is used to end most statements in Java?","`.` (period)","`:` (colon)","`;` (semicolon)","`,` (comma)","C"
"How do you write a single-line comment in Java?","`/* comment */`","`// comment`","``","`# comment`","B"
"Which data type is used to store a single character, like 'A'?","`string`","`character`","`char`","`int`","C"
"What is the result of `10 / 4` when performed with integers in Java?","`2.5`","`2`","`3`","`2.0`","B"
"Which operator is used to check if two values are equal?","`=`","`:=`","`===`","`==`","D"
"What does the acronym JVM stand for?","Java Virtual Machine","Java Variable Manager","Java Verified Module","Java Visual Machine","A"
"Which of the following is NOT a primitive data type?","`int`","`boolean`","`Array`","`double`","C"
"What is the process of creating an object from a class called?","Inheritance","Instantiation","Encapsulation","Compilation","B"
"Which keyword is used to create a new object in Java?","`make`","`create`","`new`","`alloc`","C"
"What is the output of `System.out.println(""Hello"" + "" World"");`?","`Hello + World`","`Hello World`","`HelloWorld`","Compilation Error","C"
"Which method is used to get the number of characters in a `String`?","`size()`","`length`","`count()`","`length()`","D"
"In an array, what is the index of the first element?","`1`","`a`","`0`","`-1`","C"
"Which loop structure will always execute its body at least once?","`for`","`while`","`if-else`","`do-while`","D"
"What does the `%` (modulus) operator do?","Calculates the percentage.","Returns the remainder of a division.","Multiplies two numbers.","Converts a number to a float.","B"
"Which of these is the correct way to declare an integer variable named 'score'?","`new int score;`","`variable score;`","`int score;`","`score int;`","C"
"What is the boolean data type used for?","Storing whole numbers.","Storing text.","Storing true or false values.","Storing decimal numbers.","C"
"To use the `Scanner` class for user input, which package must be imported?","`java.io`","`java.lang`","`java.util`","`java.system`","C"
"What is a 'class' in Java?","A specific instance of an object.","A variable.","A blueprint or template for creating objects.","A method.","C"
"What is the `else` statement used for?","To define the main block of code.","To specify a block of code to be executed if the `if` condition is false.","To create a loop.","To declare a variable.","B"
"Which of the following is a logical operator?","`+`","`=`","`&&`","`>`","C"
"What value does a method with a `void` return type give back?","`0`","`null`","`true`","It does not return a value.","D"
"How do you get the third element from an array named `data`?","`data[3]`","`data.get(3)`","`data[2]`","`data.get(2)`","C"
"What is 'bytecode' in the context of Java?","The source code written by the programmer.","The code that the JVM executes.","A type of comment.","A security error.","B"
"Which of the following correctly initializes an array of integers?","`int[] nums = {1, 2, 3};`","`int[] nums = (1, 2, 3);`","`int nums[] = new int(3);`","`int nums = [1, 2, 3];`","A"
"What is the purpose of a constructor?","To destroy an object.","A special method used to initialize an object.","To run the main logic of a program.","To return a value from a method.","B"
"Which comparison operator means 'not equal to'?","`<>`","`~=`","`!=`","`!==`","C"
"What is the result of the expression `true || false`?","`true`","`false`","`0`","`1`","A"
"In a `for` loop declaration `for (int i=0; i<5; i++)`, what does `i++` do?","It sets `i` to 1.","It checks if `i` is less than 5.","It initializes `i`.","It increments `i` by 1 after the loop body executes.","D"
"Which data type is most suitable for storing the value `3.14159`?","`int`","`double`","`char`","`boolean`","B"
"What is an 'object' in Java?","A blueprint or template.","A specific instance of a class.","A primitive data type.","A keyword.","B"
"How do you call a method named `calculateTotal` on an object named `myCart`?","`calculateTotal(myCart);`","`myCart.calculateTotal;`","`myCart.calculateTotal()`","`new calculateTotal(myCart);`","C"
"What is the `.length` property used for with an array?","To get the last element in the array.","To get the first element in the array.","To get the number of elements in the array.","To change the size of the array.","C"
"Which keyword is used to specify a block of code to be executed in a `switch` statement if none of the cases match?","`default`","`else`","`otherwise`","`case_else`","A"
"What is the assignment operator in Java?","`==`","`:=`","`=`","`<-`","C"
"What is the correct way to write ""Hello, World!"" to the console?","`console.log(""Hello, World!"");`","`print(""Hello, World!"");`","`System.out.println(""Hello, World!"");`","`cout << ""Hello, World!"";`","C"
"What is the process of converting a smaller data type to a larger data type called?","Narrowing conversion","Widening conversion","Explicit casting","Data loss","B"
"Which of the following is a valid method declaration that returns an integer?","`void myMethod() {}`","`int myMethod() {}`","`method myMethod() int {}`","`myMethod int() {}`","B"
"What are `public` and `private`?","Data types","Access modifiers","Loops","Objects","B"
"What is the body of a method enclosed in?","`( )` (parentheses)","`[ ]` (square brackets)","`{ }` (curly braces)","`< >` (angle brackets)","C"
"Which of these loops will run as long as the condition `x < 10` is true?","`for (x < 10)`","`while (x < 10)`","`loop (x < 10)`","`if (x < 10)`","B"
"What is the keyword `return` used for?","To stop the entire program.","To start a method.","To exit a method and optionally give back a value.","To create a new variable.","C"
"What is the `+` operator used for with `String` variables?","Addition","Multiplication","Concatenation","Comparison","C"
"If an array is declared as `int[] scores = new int[10];`, what is the largest valid index?","`10`","`9`","`11`","`0`","B"
"Which part of the `for` loop `for (A; B; C)` is the condition?","`A`","`B`","`C`","Both A and C","B"
"What will the expression `5 > 3` evaluate to?","`5`","`3`","`true`","`false`","C"
"What is the name of the concept where a variable of one type can hold an object of a subclass?","Inheritance","Polymorphism","Encapsulation","Abstraction","B"
"Which of the following is a correct way to create a `Scanner` object?","`Scanner sc = Scanner(System.in);`","`Scanner sc = new Scanner(System.in);`","`new Scanner sc = System.in;`","`Scanner sc = new Scanner();`","B"
"What is the result of `10 % 3`?","`1`","`3`","`3.33`","`0`","A"
"What is Java's principle of 'write once, run anywhere'?","Code runs only on the machine it was written on.","Compiled Java bytecode can run on any platform with a JVM.","Java code must be rewritten for each operating system.","Java only runs on Windows.","B"
"What is the `break` keyword used for inside a loop?","To skip the current iteration and continue with the next.","To exit the loop immediately.","To pause the loop.","To restart the loop.","B"
"Which of these is the correct way to assign the text 'Java' to a `String` variable?","`String name = Java;`","`String name = ""Java"";`","`String name = 'Java';`","`string name = ""Java"";`","B"
"What is a 'parameter' or 'argument' in a method?","The value the method returns.","A variable that stores the method's name.","A value passed into a method when it is called.","The body of the method.","C"
"What does the `static` keyword mean when applied to a variable?","The variable's value cannot change.","The variable belongs to the class, not to any specific object.","The variable is automatically initialized.","The variable can only be accessed by static methods.","B"
"How would you access the character 'v' in the string `String s = "Java";`?","`s[2]`","`s.get(2)`","`s.charAt(2)`","`s.character(2)`","C"
"What is the default value for an uninitialized `int` instance variable?","`null`","`0`","`1`","`undefined`","B"
"Which part of the computer executes Java bytecode?","The CPU","The RAM","The Operating System","The JVM","D"
"What is the result of the expression `!(5 == 5)`?","`true`","`false`","`5`","Compilation Error","B"
"In an `if-else if-else` structure, how many blocks can be executed at most?","`0`","`1`","`2`","All of them","B"
"What does `i += 5;` mean?","`i = i + 5;`","`i = 5;`","`i = i * 5;`","`i + 5;`","A"
"What is the purpose of 'encapsulation'?","To allow a class to inherit properties from another class.","To hide the internal state of an object and require all interaction to be performed through an object's methods.","To allow an object to take many forms.","To create a blueprint for objects.","B"
"Which of the following is a valid name for a variable in Java?","`1stName`","`first Name`","`firstName`","`first-name`","C"
"What must a non-abstract class do if it implements an interface?","It must have a constructor.","It must override all abstract methods of the interface.","It must declare all its variables as final.","It must be declared as static.","B"
"Which primitive data type would be best for storing a person's age in whole years?","`double`","`float`","`int`","`long`","C"
"What is the `new` keyword always followed by?","A variable name","A semicolon","A method call","A constructor call","D"
"What kind of error occurs when the program violates Java's syntax rules?","Runtime Error","Logic Error","Compilation Error","System Error","C"
"If a class is named `MyProgram`, what should the `.java` file be named?","`MyProgram.java`","`myprogram.java`","`Program.java`","Any name is fine.","A"
"What does `Math.sqrt(16)` return?","`4`","`4.0`","`8`","`256.0`","B"
"Which of these is used to define a block of code?","`( )`","`[ ]`","`" "`","`{ }`","D"
"What is the `continue` keyword used for in a loop?","To stop the loop.","To skip the rest of the current iteration and start the next one.","To pause the program.","To go back to the first iteration.","B"
"Which of these is the correct syntax for a multi-line comment?","`// Comment`","`/* Comment */`","``","`## Comment`","B"
"What is a `null` value?","The same as the number 0.","The same as an empty string `""`.","A special value that means 'no object' or 'no reference'.","A type of error.","C"
"Which operator has the highest precedence?","`+`","`=`","`*`","`()`","D"
"What is a `package` in Java?","A single `.java` file.","An object.","A way of grouping related classes and interfaces.","A type of loop.","C"
"What is the `import` statement used for?","To include a code file directly into another.","To make classes from other packages accessible.","To create a new object.","To start the program.","B"
"If `x` is 7, what is `x++`?","The expression's value is 7, and `x` becomes 8.","The expression's value is 8, and `x` becomes 8.","The expression's value is 7, and `x` remains 7.","This is not valid syntax.","A"
"Which data type uses the most memory?","`byte`","`int`","`short`","`long`","D"
"What is 'method overloading'?","When a subclass has a method with the same name as a superclass.","When a class has multiple methods with the same name but different parameters.","When a method has too much code.","When a method calls itself.","B"
"Which statement is used to make a decision based on a condition?","`for`","`while`","`if`","`return`","C"
"What is the superclass of all other classes in Java?","`Main`","`System`","`Object`","`Java`","C"
"How do you convert a `String` named `s` to an integer?","`(int) s`","`s.toInt()`","`Integer.parseInt(s)`","`s.getInteger()`","C"
"What is an 'infinite loop'?","A loop that runs exactly 100 times.","A loop that never executes.","A loop that runs forever because its condition is always true.","A loop with an error.","C"
"Which keyword is used in a class to inherit from another class?","`implements`","`inherits`","`extends`","`super`","C"
"What is the main difference between an array and an `ArrayList`?","An array can store primitives, an `ArrayList` cannot.","An `ArrayList` is faster than an array.","An array has a fixed size, while an `ArrayList` can grow and shrink.","An array can hold multiple data types, an `ArrayList` cannot.","C"
"Which of these would cause a `NullPointerException`?","Accessing an array element with an invalid index.","Dividing a number by zero.","Calling a method on a variable that holds a `null` reference.","Trying to open a file that does not exist.","C"
"What is the scope of a variable declared inside a method?","It is accessible from anywhere in the class.","It is accessible only within that method.","It is accessible from any class in the same package.","It is accessible globally to the entire program.","B"
"What is the correct syntax for the `OR` logical operator?","`OR`","`&`","`||`","`|`","C"
"What is the `char` data type used to store?","A sequence of characters.","A single Unicode character.","A whole number.","A true or false value.","B"
"In Java, are variable names case-sensitive?","Yes, `myVar` and `myvar` are different variables.","No, `myVar` and `myvar` are the same variable.","Only for static variables.","Only for final variables.","A"
"Which of these values could NOT be stored in a variable of type `int`?","`100`","`-5000`","`0`","`98.6`","D"
"What is the purpose of the `System.in` object?","To represent the standard output stream (console).","To represent the standard input stream (keyboard).","To represent the system's clock.","To exit the program.","B"
"Which of these will correctly get a single word of input from the user?","`scanner.getLine()`","`scanner.next()`","`scanner.read()`","`scanner.nextWord()`","B"
"What is 'inheritance'?","A mechanism where one class acquires the properties and behaviors of another class.","The process of hiding data.","The ability to take more than one form.","The process of creating an object.","A"
"What is the output of the following code? `String s1 = ""cat""; String s2 = ""cat""; System.out.println(s1 == s2);`","`true`","`false`","Compilation Error","It depends on the JVM","A"
"What is the output of the following code? `String s1 = ""dog""; String s2 = new String(""dog""; System.out.println(s1.equals(s2));`","`true`","`false`","Compilation Error","Runtime Error","A"
"Which of the following is the best way to add an element to an `ArrayList` named `list`?","`list.add(element);`","`list.insert(element);`","`list[list.size()] = element;`","`list.append(element);`","A"
"A method in a subclass has the same name and signature as a method in its superclass. What is this concept called?","Method Overloading","Method Overriding","Method Hiding","Method Duplication","B"
"What is the purpose of the `this` keyword?","To call a method from the superclass.","To refer to the current object instance.","To create a new object.","To refer to a static variable.","B"
"What will happen when you attempt to compile and run this code? `int[] arr = new int[5]; System.out.println(arr[5]);`","It prints 0.","It prints null.","It compiles but throws an `ArrayIndexOutOfBoundsException` at runtime.","It fails to compile.","C"
"If a class has multiple constructors with different parameter lists, what is this an example of?","Constructor Overriding","Inheritance","Polymorphism","Constructor Overloading","D"
"What does the `finally` block in a `try-catch` statement do?","It executes only when an exception occurs.","It executes only when no exception occurs.","It executes regardless of whether an exception is thrown or not.","It is a mandatory block for every `try` statement.","C"
"What is the key difference between an abstract class and an interface?","An interface can have instance variables, while an abstract class cannot.","An abstract class can have method implementations, while an interface (before Java 8) could not.","A class can implement multiple abstract classes.","An interface can be instantiated.","B"
"Which of these will cause a `NullPointerException`?","`String s = null; int len = s.length();`","`String s = """"; int len = s.length();`","`int[] arr = {}; int len = arr.length;`","`int x = 0; int y = x / 1;`","A"
"What is the output of this code snippet? `for (int i = 0; i < 3; i++) { System.out.print(i + "" ""); }`","`0 1 2`","`1 2 3`","`0 1 2 3`","`0 1`","A"
"What is the concept of wrapping data (variables) and code acting on the data (methods) together as a single unit?","Inheritance","Polymorphism","Abstraction","Encapsulation","D"
"How do you access a static method `myMethod()` of a class `MyClass`?","`MyClass obj = new MyClass(); obj.myMethod();`","`MyClass.myMethod();`","`MyClass->myMethod();`","Both A and B are valid.","D"
"What is the value of `result`? `int x = 10; int result = (x > 5) ? 100 : 200;`","`10`","`5`","`100`","`200`","C"
"Which of the following is true about `String` objects in Java?","They are mutable.","They can be changed after creation.","They are immutable.","They are stored on the stack.","C"
"What does the `super` keyword do in a constructor?","It calls a constructor from the current class.","It refers to the current object instance.","It calls a constructor from the superclass.","It is used to access static members.","C"
"Which collection does NOT allow duplicate elements?","`ArrayList`","`LinkedList`","`HashSet`","`Vector`","C"
"What is the output? `System.out.println(5 + 3 * 2);`","`16`","`11`","`13`","`30`","B"
"In a `switch` statement, what happens if a `break` statement is omitted from a case?","The program will throw a compilation error.","The program will exit the switch statement.","Execution will 'fall through' to the next case.","The default case will be executed.","C"
"What is the `instanceof` operator used for?","To check if an object is an instance of a particular class, subclass, or interface.","To create a new instance of an object.","To check if a class is static.","To compare two object references.","A"
"What is the main advantage of an enhanced for-loop (for-each loop)?","It is faster than a standard for-loop.","It can iterate backwards over a collection.","It simplifies the syntax for iterating over collections and arrays.","It allows the removal of elements during iteration.","C"
"What is the process of converting a primitive type to its corresponding wrapper class object called?","Unboxing","Casting","Autoboxing","Parsing","C"
"Consider `Animal a = new Dog();`. This is an example of...","Encapsulation","Inheritance","Polymorphism","Abstraction","C"
"Which method from the `Object` class should be overridden to ensure proper behavior in hash-based collections like `HashMap`?","`toString()`","`finalize()`","`equals()` and `hashCode()`","`clone()`","C"
"What does the `trim()` method of the `String` class do?","It removes all whitespace from the string.","It removes whitespace from the beginning of the string.","It removes whitespace from the end of the string.","It removes whitespace from both the beginning and end of the string.","D"
"What is the output? `int i = 5; System.out.println(i++);`","`6`","`5`","`4`","Compilation Error","B"
"What is the output? `int i = 5; System.out.println(++i);`","`6`","`5`","`4`","Compilation Error","A"
"Which of these exceptions is an example of an 'unchecked' exception?","`IOException`","`SQLException`","`NullPointerException`","`FileNotFoundException`","C"
"Which access modifier makes a member accessible only within its own class?","`public`","`protected`","`default`","`private`","D"
"How would you get the number of elements currently in an `ArrayList` named `items`?","`items.length`","`items.size`","`items.count()`","`items.size()`","D"
"What is the return type of the `.equals()` method in the `Object` class?","`int`","`String`","`Object`","`boolean`","D"
"What is the correct way to compare the content of two strings, `s1` and `s2`?","`s1 == s2`","`s1.equals(s2)`","`s1.compare(s2)`","`s1 = s2`","B"
"What is the value of `c`? `char c = ""Java"".charAt(2);`","`'J'`","`'a'`","`'v'`","`'a'` (the second one)","C"
"What is the default constructor?","A constructor that takes no arguments.","A constructor that is automatically provided by the compiler if no other constructor is defined.","A constructor that initializes all variables to default values.","The first constructor defined in a class.","B"
"If a method is declared as `static`, what is true about it?","It must be called on an instance of the class.","It can access instance variables of the class directly.","It can be called without creating an instance of the class.","It cannot have any parameters.","C"
"Which statement about interfaces is true?","A class can implement only one interface.","An interface can be instantiated using the `new` keyword.","A class can implement multiple interfaces.","Interfaces can have constructors.","C"
"What is the output of the following loop? `for(int i=5; i>0; i--) { System.out.print(i); }`","`54321`","`5432`","`43210`","`12345`","A"
"What is the purpose of the `Scanner` class's `nextLine()` method after using `nextInt()`?","To read the next integer.","To clear the input buffer of the newline character.","To skip the next line of input.","To convert the integer to a line of text.","B"
"Which of these is a valid declaration for the `main` method?","`public static void main(String args)`","`public void main(String[] args)`","`public static void main(String[] args)`","`static public void main(String args[])`","C"
"What does 'casting' refer to in Java?","Throwing an exception.","Creating an object.","Explicitly converting a value from one data type to another.","Catching an error.","C"
"If `MyClass` inherits from `MySuperClass`, which of these constructor calls is valid inside `MyClass`'s constructor?","`MySuperClass();`","`super();`","`this.super();`","`new MySuperClass();`","B"
"What is the output? `String str = ""abcde""; System.out.println(str.substring(1, 4));`","`bcd`","`bcde`","`abc`","`b`","A"
"Which of these statements will successfully create an `ArrayList` to hold `String` objects?","`ArrayList<> list = new ArrayList();`","`ArrayList<String> list = new ArrayList();`","`ArrayList list = new ArrayList<String>();`","`ArrayList<String> list = new ArrayList<String>();`","D"
"What is the index of the last element in an array of length `N`?","`N`","`N-1`","`N+1`","`0`","B"
"Which of the following is true for an abstract method?","It has a method body with no code.","It must be declared `final`.","It has no method body and must be implemented by a subclass.","It must be `private`.","C"
"What is the output? `System.out.println(10 / 4.0);`","`2`","`2.0`","`2.5`","Compilation Error","C"
"What is the purpose of the `break` statement in a `switch`?","To end the program.","To skip the rest of the cases and exit the `switch` block.","To continue to the next case.","To mark the default option.","B"
"When a method calls itself, it is known as...","Recursion","Overloading","Overriding","Iteration","A"
"Which of these is the correct way to get the first element from an `ArrayList` named `list`?","`list[0]`","`list.first()`","`list.get(0)`","`list.element(0)`","C"
"What is a 'package private' or 'default' access level?","Members are accessible only within the same class.","Members are accessible from anywhere.","Members are accessible only within the same package.","Members are accessible within the same package and by subclasses.","C"
"What is the output? `boolean a = true; boolean b = false; System.out.println(a && b);`","`true`","`false`","`1`","`0`","B"
"Which of these is a reference type?","`int`","`char`","`double`","`String`","D"
"What is the value of `name` after this code? `String name = ""  Java  ""; name = name.trim();`","`""  Java  ""`","`""Java""`","`""Java  ""`","`""  Java""`","B"
"What is the role of a 'getter' method (e.g., `getName()`) in encapsulation?","To set the value of a private field.","To provide read-only access to a private field.","To initialize an object.","To perform a calculation.","B"
"What is the initial value of elements in an array of `boolean`?","`1`","`0`","`true`","`false`","D"
"Which keyword prevents a class from being subclassed?","`static`","`private`","`final`","`abstract`","C"
"Which of these is the correct way to declare a constant that is available globally?","`final PI = 3.14;`","`static const double PI = 3.14;`","`public static final double PI = 3.14;`","`let PI = 3.14;`","C"
"What is the relationship between a class and an object?","A class is an instance of an object.","An object is an instance of a class.","They are the same thing.","A class is a method of an object.","B"
"What is the output? `System.out.println(""Result: "" + (2 + 3));`","`Result: 23`","`Result: 5`","`Result: 2 + 3`","Compilation Error","B"
"When is the code in a `catch` block executed?","Always.","Never.","Only when an exception of the specified type occurs in the `try` block.","Only when there are no exceptions.","C"
"What does the `indexOf()` method of the `String` class return if the substring is not found?","`0`","`null`","`-1`","It throws an exception.","C"
"What is the output? `int[] nums = {2, 4, 6}; for(int n : nums) { System.out.print(n); }`","`246`","`2, 4, 6`","`012`","`{2, 4, 6}`","A"
"If you want a method to be available to any class in any package, which access modifier should you use?","`private`","`protected`","`public`","`default`","C"
"Which of these data structures stores key-value pairs?","`ArrayList`","`HashSet`","`HashMap`","`LinkedList`","C"
"What will happen? `double d = 100.5; int i = (int) d; System.out.println(i);`","It prints `100.5`.","It prints `100`.","It prints `101`.","It throws a runtime error.","B"
"What is the `main` purpose of an `interface`?","To define a contract of methods that a class must implement.","To provide reusable code through inheritance.","To create objects directly.","To store constant variables.","A"
"What is the output? `String s = ""hello""; s.toUpperCase(); System.out.println(s);`","`HELLO`","`hello`","`Hello`","`null`","B"
"Why would you use a `StringBuilder` instead of a `String` for many concatenations?","`StringBuilder` is immutable.","`StringBuilder` uses less memory.","`StringBuilder` is faster because it is mutable, avoiding the creation of new objects for each change.","`StringBuilder` is thread-safe.","C"
"What does the `continue` statement do inside a loop?","It terminates the loop immediately.","It restarts the loop from the beginning.","It skips the remaining code in the current iteration and proceeds to the next one.","It pauses the loop.","C"
"What is the value of `z`? `int x=5; int y=2; double z = x/y;`","`2.5`","`2.0`","`2`","Compilation Error","B"
"In an `if (condition)` statement, what must the `condition` evaluate to?","An integer","A string","A boolean","An object","C"
"What is the output? `int temp = 90; if (temp > 90) { System.out.print(""A""); } else { System.out.print(""B""); }`","`A`","`B`","`AB`","No output","B"
"Which of these cannot be a variable name in Java?","`_variable`","`$variable`","`myVariable`","`new`","D"
"What is the purpose of the `toString()` method in the `Object` class?","To convert an object to an integer.","To return a string representation of an object.","To check if two objects are equal.","To create a string from a character array.","B"
"Which of these is a correct loop to print numbers 0 through 4?","`for(int i=1; i<5; i++)`","`for(int i=0; i<=5; i++)`","`for(int i=0; i<5; i++)`","`for(int i=0; i<=4; i++)`","D"
"When an object is no longer referenced by any part of your program, what happens to it?","It remains in memory forever.","It becomes eligible for garbage collection.","It causes a `NullPointerException`.","The programmer must manually delete it.","B"
"What is the correct way to get the length of an array named `ages`?","`ages.length()`","`ages.size()`","`ages.length`","`ages.capacity()`","C"
"Which of these is NOT a valid primitive type?","`float`","`byte`","`string`","`long`","C"
"What is the difference between method overriding and overloading?","Overriding is in the same class; overloading is in a subclass.","Overloading uses the same method signature; overriding uses a different one.","Overriding is resolved at runtime; overloading is resolved at compile time.","They are the same concept.","C"
"What is the output of the following? `System.out.println('a' + 1);`","`a1`","`b`","`98`","Compilation Error","C"
"What is the purpose of a 'setter' method (e.g., `setName()`)?","To get the value of a private field.","To provide a controlled way to modify a private field.","To check the type of a field.","To make a field read-only.","B"
"What does `Math.random()` return?","A random integer.","A random double between 0.0 (inclusive) and 1.0 (exclusive).","A random boolean.","A random character.","B"
"Which of these is used to define a class that cannot be instantiated but can be subclassed?","`final`","`static`","`private`","`abstract`","D"
"What happens if an exception is thrown in a `try` block and there is no matching `catch` block?","The program continues as if nothing happened.","The `finally` block is skipped.","The program terminates.","The exception is ignored.","C"
"What is the output? `boolean isReady = false; if (isReady = true) { System.out.print(""Ready""); }`","`Ready`","No output","Compilation Error","`false`","A"
"Which of these is an example of explicit type casting (narrowing)?","`double d = 10;`","`int i = 10.5;`","`int i = (int) 10.5;`","`double d = 10L;`","C"
"What is a 'field' in a Java class?","A method.","A constructor.","A variable inside a class.","An object.","C"
"What is the initial capacity of a default `ArrayList`?","`0`","`1`","`8`","`10`","D"
"Which of these is the correct way to check if a `String` `s` is empty?","`s == """"`","`s.equals("""")`","`s.isEmpty()`","Both B and C are correct","D"
"What is the correct way to use the `OR` operator in an `if` statement?","`if (x > 5 OR y < 10)`","`if (x > 5 || y < 10)`","`if (x > 5 | y < 10)`","`if (x > 5 && y < 10)`","B"
"A class that inherits from another class is called a...","Superclass","Parent class","Subclass","Base class","C"
"What is the result of `""Java"".equals(""java"")`?","`true`","`false`","Compilation Error","`1`","B"
"What is the result of `""Java"".equalsIgnoreCase(""java"")`?","`true`","`false`","Compilation Error","`0`","A"
"How do you remove an element at index `i` from an `ArrayList` `list`?","`list.delete(i)`","`list.remove(i)`","`list.erase(i)`","`list[i] = null;`","B"
"If a variable is declared inside a `for` loop, where can it be accessed?","Only inside that `for` loop.","Anywhere inside the method containing the loop.","Anywhere in the class.","Anywhere in the package.","A"
"What is the purpose of the `import` statement?","To load a class into memory.","To tell the compiler where to find the definitions of classes used in the code.","To copy code from another file.","To start the execution of a program.","B"
"What does `Integer.parseInt(""123"")` do?","It returns the integer `123`.","It returns the string `""123""`.","It returns the character `'1'`.","It throws a `NumberFormatException`.","A"
"Which statement is true about `static` variables?","Each object of the class has its own copy.","They can only be accessed by `static` methods.","There is only one copy of the variable, shared among all objects of the class.","They must be declared as `final`.","C"
"What is the best loop to use when you know exactly how many times you need to iterate?","`while` loop","`do-while` loop","`for` loop","enhanced for-loop","C"
"What is the value of `result`? `int result = 5 + 2 * 3;`","`21`","`11`","`13`","`10`","B"
"What is the data type of the expression `5 / 2.0`?","`int`","`float`","`long`","`double`","D"
"What is the value of `result`? `int result = 10 / 2 * 5;`","`1`","`25`","`10`","`2.5`","B"
"What is the data type of the expression `10L + 0.5f`?","`long`","`int`","`double`","`float`","D"
"What is the value of `result`? `int result = 12 % 5 + 3;`","`2`","`5`","`0`","`1`","B"
"What is the data type of the expression `(short) 5 + (byte) 2`?","`byte`","`short`","`int`","`long`","C"
"What is the value of `x` after this code? `int x = 10; x += 5 * 2;`","`30`","`20`","`25`","`17`","B"
"What is the data type of the expression `'A' + 1`?","`char`","`String`","`int`","`long`","C"
"What is the value of `result`? `boolean result = 5 > 3 && 4 < 2;`","`true`","`false`","Compilation Error","Runtime Error","B"
"What is the data type of the expression `5 + "" + 3`?","`int`","`char`","`String`","`double`","C"
"What is the value of `result`? `int result = 7 - 4 + 2;`","`1`","`5`","`-1`","`9`","B"
"What is the data type of `x`? `var x = 100D + 20;`","`int`","`float`","`long`","`double`","D"
"What is the value of `x`? `int x = 5; int y = ++x;`","`5`","`6`","`10`","`4`","B"
"What is the value of `y`? `int x = 5; int y = x++;`","`5`","`6`","`10`","`4`","A"
"What is the data type of the expression `1 / 2`?","`int`","`double`","`float`","`long`","A"
"What is the value of `result`? `int result = 10 * (5 - 3);`","`47`","`20`","`50`","`7`","B"
"What is the data type of the expression `5.0f * 2L`?","`double`","`long`","`int`","`float`","D"
"What is the value of the expression `"" + 5 + 3`?","`""8""`","`""53""`","`8`","`53`","B"
"What is the value of the expression `5 + 3 + ""`?","`""8""`","`""53""`","`8`","`53`","A"
"What is the data type of the expression `true || false && true`?","`boolean`","`int`","`String`","Compilation Error","A"
"What is the value of `result`? `int result = 15 / 4;`","`3.75`","`4`","`3`","`3.0`","C"
"What is the data type of the expression `(float) 10 / 3`?","`int`","`double`","`float`","`long`","D"
"What is the value of `a` after this code? `int a = 10; a = a++;`","`9`","`10`","`11`","`1`","B"
"What is the data type of the expression `5 * 2.0`?","`int`","`float`","`double`","`long`","C"
"What is the value of `result`? `boolean result = !(5 == 3);`","`true`","`false`","`5`","`3`","A"
"Which operator has the highest precedence?","`+`","`=`","`*`","`()`","D"
"What is the data type of `x`? `byte b = 10; short s = 20; var x = b + s;`","`byte`","`short`","`int`","`long`","C"
"What is the value of `result`? `int result = 2 + 8 / 4 * 2;`","`5`","`6`","`2.5`","`8`","B"
"What is the data type of the expression `1.0 * 'a'`?","`char`","`int`","`long`","`double`","D"
"What is the value of `result`? `int result = 3 << 2;` (Bitwise left shift)","`12`","`6`","`1`","`0.75`","A"
"What is the data type of the expression `5 > 2 ? 1.0 : 2L`?","`int`","`long`","`double`","`Object`","C"
"What is the value of `result`? `int result = 10 % 3 * 4;`","`12`","`2`","`4`","`0`","C"
"What is the data type of the expression `5 + 3L`?","`int`","`double`","`float`","`long`","D"
"What is the value of `result`? `int x = 2; int result = 5 + x++ * 3;`","`11`","`21`","`13`","`12`","A"
"What is the value of `result`? `int x = 2; int result = 5 + ++x * 3;`","`11`","`14`","`24`","`13`","B"
"What is the data type of `z`? `float x = 1.0f; double y = 2.0; var z = x + y;`","`float`","`double`","`int`","`long`","B"
"What is the value of `result`? `int result = -5 + 8 * 2;`","`6`","`11`","`26`","`21`","B"
"What is the data type of the expression `"" + 'a' + 'b'`?","`char`","`int`","`String`","`char[]`","C"
"What is the value of `result`? `boolean result = 5 > 3 || 4 < 2;`","`true`","`false`","Compilation Error","Runtime Error","A"
"Which operator has a right-to-left associativity?","`*`","`+`","`/`","`=`","D"
"What is the value of `x` after execution? `int x = 3; x *= 2 + 5;`","`11`","`13`","`21`","`16`","C"
"What is the data type of the expression `new String(""a"") + new Object()`?","`Object`","`String`","`char[]`","Compilation Error","B"
"What is the value of `result`? `int result = 20 / 10 / 2;`","`4`","`1`","`0`","`2`","B"
"What is the data type of the expression `100 / 0.0`?","`int`","`float`","`double`","It throws an exception.","C"
"What is the value of `result`? `int result = 2 * 3 % 2;`","`0`","`1`","`2`","`3`","A"
"What is the data type of `x`? `char c = 'A'; byte b = 1; var x = c + b;`","`char`","`byte`","`int`","`short`","C"
"What is the value of `result`? `int result = 1 + 2 * 3 + 4;`","`11`","`13`","`21`","`10`","A"
"What is the data type of the expression `5 > 2 ? 'a' : 100`?","`char`","`int`","`Object`","`double`","B"
"What is the value of `i`? `int i = 10; i = i-- * 2;`","`20`","`18`","`22`","`9`","A"
"What is the data type of the expression `(10/3f)`?","`int`","`double`","`float`","`long`","C"
"What is the value of `x` after this line? `int x = 10; x = --x + 2;`","`11`","`12`","`10`","`9`","A"
"What is the data type of the expression `5 + (byte) 3`?","`byte`","`int`","`long`","`double`","B"
"What is the value of the expression `true == false ? 1 : 0`?","`true`","`false`","`1`","`0`","D"
"What is the data type of the expression `3.14 * 2`?","`int`","`float`","`double`","`long`","C"
"What is the value of `result`? `int result = 8 >> 1;` (Bitwise right shift)","`16`","`8`","`4`","`2`","C"
"What is the data type of the expression `5 / 2 * 2.0`?","`int`","`float`","`double`","`long`","C"
"What is the value of `result`? `int result = 5 / 2 * 2;`","`4`","`5`","`4.0`","`5.0`","A"
"What is the data type of `z`? `int x = 1; long y = 2; var z = x + y;`","`int`","`double`","`float`","`long`","D"
"What is the value of `result`? `boolean result = 10 != 5 * 2;`","`true`","`false`","Compilation Error","Runtime Error","B"
"What is the data type of `c + s`? `char c = 'a'; short s = 1;`","`char`","`short`","`int`","`long`","C"
"What is the value of `result`? `int result = 6 - (2 + 1) * 2;`","`8`","`6`","`0`","`-2`","C"
"What is the data type of the expression `(double) (5/2)`?","`int`","`float`","`double`","`long`","C"
"What is the value of the expression `(double) 5 / 2`?","`2.0`","`2`","`2.5`","`3.0`","C"
"What is the data type of `x`? `short s = 5; var x = s * 2;`","`short`","`int`","`long`","`double`","B"
"What is the value of `result`? `int result = 5 & 3;` (Bitwise AND)","`1`","`3`","`5`","`7`","A"
"What is the data type of the expression `5.0 / 2F`?","`int`","`float`","`double`","`long`","C"
"What is the value of `result`? `int result = 2 + 2 * (2 + 2);`","`16`","`10`","`12`","`8`","B"
"What is the data type of the expression `1 + 2 + "" + 3 + 4`?","`int`","`double`","`char`","`String`","D"
"What is the value of the expression `1 + 2 + "" + 3 + 4`?","`""1234""`","`""334""`","`""10""`","`""37""`","B"
"What is the data type of `x`? `byte b = 1; b = b * 2;`","`byte`","`int`","`long`","Compilation Error","D"
"What is the value of `result`? `boolean result = false || true && false;`","`true`","`false`","Compilation Error","Runtime Error","B"
"What is the data type of the expression `Math.sqrt(4)`?","`int`","`float`","`double`","`long`","C"
"What is the value of `result`? `int result = 10; result /= 2 + 3;`","`5`","`8`","`2`","`3`","C"
"What is the data type of `c`? `var c = 'a';`","`int`","`String`","`char`","`Object`","C"
"What is the value of `result`? `int result = 10 - 2 - 3;`","`5`","`11`","`9`","`6`","A"
"What is the data type of `x`? `float f = 1.0f; var x = f/2;`","`int`","`double`","`float`","`long`","C"
"What is the value of `result`? `int result = 3 * (1 + 2) / 2;`","`3`","`4.5`","`4`","`3.5`","C"
"What is the data type of the expression `10 > 5`?","`int`","`String`","`boolean`","`Object`","C"
"What is the value of `result`? `int result = 5 | 6;` (Bitwise OR)","`4`","`5`","`6`","`7`","D"
"What is the data type of `x`? `double d = 1; int i = 2; var x = d + i;`","`int`","`long`","`double`","`float`","C"
"What is the value of `result`? `int result = (int) 3.14 * 2;`","`6.28`","`6`","`7`","`5`","B"
"What is the data type of the expression `'a' + ""`?","`char`","`int`","`String`","`Object`","C"
"What is the value of `x`? `boolean b = true; int x = b ? 10 : 20;`","`true`","`10`","`20`","Compilation Error","B"
"What is the data type of the expression `1 / 2.0f`?","`int`","`double`","`float`","`long`","C"
"What is the value of `result`? `int result = 10 * 2 / 5;`","`4`","`1`","`25`","`10`","A"
"What is the data type of `x`? `byte b1 = 1; byte b2 = 2; var x = b1 + b2;`","`byte`","`short`","`int`","`long`","C"
"What is the value of `result`? `int result = 10 + -5;`","`15`","`5`","`-5`","`-15`","B"
"What is the data type of the expression `5.0 % 2.0`?","`int`","`double`","`float`","`long`","B"
"What is the value of `result`? `String result = ""A"" + 'B' + 65;`","`""AB65""`","`""A130""`","Compilation Error","`""A66""`","A"
"What is the data type of the expression `1 + 2L * 3.0f`?","`long`","`int`","`float`","`double`","D"
"What is the value of `x`? `int x = 10; x = x * 2 + x++;`","`30`","`31`","`20`","`21`","A"
"What is the data type of `x`? `final var x = 10;`","`final`","`Object`","`var`","`int`","D"
"What is the value of `result`? `int result = ~5;` (Bitwise complement)","`5`","`-5`","`6`","`-6`","D"
"What is the data type of `x`? `int i = 1; var x = i < 2;`","`int`","`double`","`boolean`","`Object`","C"
"What is the value of `result`? `int result = (1 + 2 + 3) * 2;`","`13`","`9`","`12`","`11`","C"
"What is the data type of `x`? `var x = 1.23;`","`float`","`double`","`int`","`long`","B"
